### ISSUE TITLE
Token StartAttribute in state Element Content would result in an invalid XML document.

### ISSUE THREAD

**Issue by johanvergeer** [wojtpl2/ExtendedXmlSerializer#257]
When an element contains both an attribute and an element the exception `Token StartAttribute in state Element Content would result in an invalid XML document.` is thrown. This seems to have something to do with `EnableMemberExceptionHandling()`.

For this sample I have the following classes:

```csharp
public class RootElement
{
    public Bar Bar { get; set; }
    public string Version { get; set; }
}

public class Bar
{
    public string Name { get; set; }
}
```

# Tests

## Test 1

- Without `EnableMemberExceptionHandling()`
- `RootElement` has an attribute named `Version`, which is set.
- `RootElement` has an element `Bar`, which is set.

```csharp
var c = new ConfigurationContainer()
    .ConfigureType<RootElement>()
        .Name("Root")
        .Member(re => re.Version)
            .Attribute()

    .ConfigureType<Bar>()

    .Create();

var r = new RootElement
{
    Version = "1",
    Bar = new Bar { Name = "bar" },
};

r.SerializeToFile();

c.Cycle(r).Should().BeEquivalentTo(r);
```

This gives the following result:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Root UniformsVersion="1" xmlns="clr-namespace:Unittests.Serialization;assembly=Unittests">
  <Bar>
    <Name>bar</Name>
  </Bar>
</Root>
```

## Test 2

- With `EnableMemberExceptionHandling()`
- `RootElement` has an attribute named `Version`, which is set.
- `RootElement` has an element `Bar`, which is set.

```csharp
var c = new ConfigurationContainer()
    .EnableMemberExceptionHandling()
    .ConfigureType<RootElement>()
        .Name("Root")
        .Member(re => re.Version)
            .Attribute()

    .ConfigureType<Bar>()

    .Create();

var r = new RootElement
{
    Version = "1",
    Bar = new Bar { Name = "bar" },
};

r.SerializeToFile();

c.Cycle(r).Should().BeEquivalentTo(r);
```

Which throws the following stacktrace:

```
Test Name:	Unittests.Serialization.SerializeAttributesSpec.SerializeAttributes
Test FullName:	Unittests.Serialization.SerializeAttributesSpec.SerializeAttributes
Test Source:	C:\Workspace\Unittests\Serialization\SerializeAttributes.cs : line 78
Test Outcome:	Failed
Test Duration:	0:00:00,602

Result StackTrace:	
bij ExtendedXmlSerializer.ExtensionModel.Content.Members.MemberExceptionHandlingExtension.MemberSerializer.Write(IFormatWriter writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Content\Members\MemberExceptionHandlingExtension.cs:regel 94
   bij ExtendedXmlSerializer.ContentModel.Members.MemberListWriter.Write(IFormatWriter writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberListWriter.cs:regel 36
   bij ExtendedXmlSerializer.ContentModel.Serializer`1.Write(IFormatWriter writer, T instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:regel 47
   bij ExtendedXmlSerializer.ContentModel.Content.Enclosure`1.Write(IFormatWriter writer, T instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Content\Enclosure.cs:regel 51
   bij ExtendedXmlSerializer.ContentModel.SerializerAdapter`1.Write(IFormatWriter writer, T instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\SerializerAdapter.cs:regel 66
   bij ExtendedXmlSerializer.Write`1.Execute(Writing`1 parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Write.cs:regel 43
   bij ExtendedXmlSerializer.Serializer`2.Serialize(TWrite writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Serializer.cs:regel 41
   bij ExtendedXmlSerializer.ExtensionModel.Xml.ExtendedXmlSerializer.Serialize(XmlWriter writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\ExtendedXmlSerializer.cs:regel 40
   bij Unittests.Serialization.Support.Extensions.SerializeToFile(Object object, IExtendedXmlSerializer serializer, String fileName) in C:\Workspace\Unittests\Serialization\Support\Extensions.cs:regel 40
   bij Unittests.Serialization.SerializeAttributesSpec.SerializeAttributes() in C:\Workspace\Unittests\Serialization\SerializeAttributes.cs:regel 119
----- Inner Stack Trace -----
   bij System.Xml.XmlWellFormedWriter.ThrowInvalidStateTransition(Token token, State currentState)
   bij System.Xml.XmlWellFormedWriter.AdvanceState(Token token)
   bij System.Xml.XmlWellFormedWriter.WriteStartAttribute(String prefix, String localName, String namespaceName)
   bij System.Xml.XmlWriter.WriteAttributeString(String localName, String value)
   bij ExtendedXmlSerializer.ExtensionModel.Xml.XmlWriter.Content(IIdentity property, String content) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\XmlWriter.cs:regel 120
   bij ExtendedXmlSerializer.ContentModel.Format.ContextualWriter`1.Write(IFormatWriter writer, T instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Format\ContextualWriter.cs:regel 40
   bij ExtendedXmlSerializer.ContentModel.DecoratedWriter`1.Write(IFormatWriter writer, T instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\DecoratedWriter.cs:regel 43
   bij ExtendedXmlSerializer.ContentModel.DecoratedWriter`1.Write(IFormatWriter writer, T instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\DecoratedWriter.cs:regel 43
   bij ExtendedXmlSerializer.ContentModel.Serializer`1.Write(IFormatWriter writer, T instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:regel 47
   bij ExtendedXmlSerializer.ContentModel.Properties.Property`1.Write(IFormatWriter writer, T instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Properties\Property.cs:regel 47
   bij ExtendedXmlSerializer.ContentModel.Properties.ConverterProperty`1.Write(IFormatWriter writer, T instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Properties\ConverterProperty.cs:regel 41
   bij ExtendedXmlSerializer.ContentModel.GenericSerializerAdapter`1.Write(IFormatWriter writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\GenericSerializerAdapter.cs:regel 36
   bij ExtendedXmlSerializer.ContentModel.Members.MemberSerializers.Writer.Write(IFormatWriter writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberSerializers.cs:regel 107
   bij ExtendedXmlSerializer.ContentModel.Members.MemberSerializer.Write(IFormatWriter writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberSerializer.cs:regel 46
   bij ExtendedXmlSerializer.ContentModel.Members.PropertyMemberSerializer.Write(IFormatWriter writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\PropertyMemberSerializer.cs:regel 36
   bij ExtendedXmlSerializer.ExtensionModel.Content.Members.MemberExceptionHandlingExtension.MemberSerializer.Write(IFormatWriter writer, Object instance) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Content\Members\MemberExceptionHandlingExtension.cs:regel 90
Result Message:	
System.InvalidOperationException : An exception was encountered while serializing member 'Unittests.Serialization.RootElement.Version'.  Provided instance is 'Unittests.Serialization.RootElement'.
---- System.InvalidOperationException : Token StartAttribute in state Element Content would result in an invalid XML document..
```

## Test 3

- With `EnableMemberExceptionHandling()`
- `RootElement` has an attribute named `Version`, which is NOT set.
- `RootElement` has an element `Bar`, which is set.

```csharp
var c = new ConfigurationContainer()
    .EnableMemberExceptionHandling()
    .ConfigureType<RootElement>()
        .Name("Root")
        .Member(re => re.Version)
            .Attribute()

    .ConfigureType<Bar>()

    .Create();

var r = new RootElement
{
    //Version = "1",
    Bar = new Bar { Name = "bar" },
};

r.SerializeToFile();

c.Cycle(r).Should().BeEquivalentTo(r);
```

which has this result:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Root xmlns="clr-namespace:Unittests.Serialization;assembly=Common.Unittests">
  <Bar>
    <Name>bar</Name>
  </Bar>
</Root>
```

## Test 4

- With `EnableMemberExceptionHandling()`
- `RootElement` has an attribute named `Version`, which is set.
- `RootElement` has an element `Bar`, which is NOT set.

```csharp
var c = new ConfigurationContainer()
    .EnableMemberExceptionHandling()
    .ConfigureType<RootElement>()
        .Name("Root")
        .Member(re => re.Version)
            .Attribute()

    .ConfigureType<Bar>()

    .Create();

var r = new RootElement
{
    Version = "1",
    //Bar = new Bar { Name = "bar" },
};

r.SerializeToFile(c, @"C:\Users\johan.SERVER-PARLANDO\AppData\Local\Temp\xml.xml");

c.Cycle(r).Should().BeEquivalentTo(r);
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<Root Version="1" xmlns="clr-namespace:Common.Unittests.Serialization;assembly=Common.Unittests" />
```

**Comment by Mike-EEE** [comment]
Nice catch @johanvergeer and thank you for the thorough description and test scenarios.  It made it easier to track down.  I have committed a fix into the preview feed.  Please give it a try and let me know if you run into any further issues around this.

https://www.myget.org/F/wojtpl2/api/v3/index.json

(Note: If you do run into issues, it may be a caching problem with Nuget and how we version our assemblies.  Please try deleting all versions of ExtendedXmlSerializer from your nuget cache and see if that fixes it.)

**Comment by johanvergeer** [comment]
Hi @Mike-EEE ,

I just downloaded the latest 2.1.21 version (after deleting the cache), but the error still shows.

**Comment by Mike-EEE** [comment]
Boh.  Are you by chance able to successfully duplicate on your end the following test that was committed as part of the fix?

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/bf198270a37e400139014ba31db1b525fbd1df8a/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue257Tests.cs#L13-L34

If that test fails for you then we can be sure it's a caching issue.

If I recall correctly, you had a caching issue previously that went away with a reboot.  Perhaps try also restarting Visual Studio first before rebooting.

If that test _does_ pass and your code still fails, then we have another bug I will have to trace down.

**Comment by Mike-EEE** [comment]
Oh, I know.  Perhaps try cleaning your solution as well in addition to clearing your nuget cache.  It's probably doing a comparison on version and not copying it over because the version is the same and it's already in your `bin` folder.

@wojtpl2 we really need to have the continuous deployment on myget kick off a new version with each commit. 😁

**Comment by johanvergeer** [comment]
This seems to be fixed. 

Thanks

**Comment by johanvergeer** [comment]
> @wojtpl2 we _really_ need to have the continuous deployment on myget kick off a new version with each commit. 😁

That would be awesome

**Comment by Mike-EEE** [comment]
Cool!  Glad we got that one.  I will circle deploying .21 next Tuesday to account for any other issues that might pop up during that time. 👍

**Comment by Mike-EEE** [comment]
This has been deployed to `2.1.21`: https://www.nuget.org/packages/ExtendedXmlSerializer/

Please let us know if you encounter any further issues/questions/concerns around this and we will do our best to assist you.

Closing for now. 👍
